### ISSUE TITLE
Sweden Visa Checklist

### ISSUE THREAD

**Issue by rahlk** [rahlk/Randoms#7]
- [ ] Visa application form 119031
- [ ] Appendix form 210021
- [ ] original passport with photocopy
- [ ] us visa with photocopy
- [ ] i20 with photocopy
- [x] last 3 months financial statement
- [x] letter of invitation with conference registration receipt
- [x] flight tickets
- [x] hotel accommodation
- [x] travel insurance
- [x] 2 passport size photos
- [x] College enrollment certificate (which you can get from my pack)
- [x] employment NOC (from kathy)
- [x] visa appointment receipt
